// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvtM22diwNFWeEvS1x2RS7Oc1srbE-AK4',
    appId: '1:62265093407:web:609caad51edb0fa642942a',
    messagingSenderId: '62265093407',
    projectId: 'restaurant-92bcb',
    authDomain: 'restaurant-92bcb.firebaseapp.com',
    storageBucket: 'restaurant-92bcb.appspot.com',
    measurementId: 'G-866735P72N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRAnRy6L5qDfeJYv1Ar3uN7EeHUPt7rCg',
    appId: '1:62265093407:android:cc33d2a1e57d2c8242942a',
    messagingSenderId: '62265093407',
    projectId: 'restaurant-92bcb',
    storageBucket: 'restaurant-92bcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCai8_Cj6KBCCeLPKUiIx8xBHAt3sEmzhI',
    appId: '1:62265093407:ios:e59fe1d38c983adc42942a',
    messagingSenderId: '62265093407',
    projectId: 'restaurant-92bcb',
    storageBucket: 'restaurant-92bcb.appspot.com',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCai8_Cj6KBCCeLPKUiIx8xBHAt3sEmzhI',
    appId: '1:62265093407:ios:e59fe1d38c983adc42942a',
    messagingSenderId: '62265093407',
    projectId: 'restaurant-92bcb',
    storageBucket: 'restaurant-92bcb.appspot.com',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvtM22diwNFWeEvS1x2RS7Oc1srbE-AK4',
    appId: '1:62265093407:web:3ff58b2cb69a8f2342942a',
    messagingSenderId: '62265093407',
    projectId: 'restaurant-92bcb',
    authDomain: 'restaurant-92bcb.firebaseapp.com',
    storageBucket: 'restaurant-92bcb.appspot.com',
    measurementId: 'G-ZW9SPR6FZ2',
  );

}